//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public long IDCar { get; set; }
        public string Number { get; set; }
        public long Region { get; set; }
        public string VIN { get; set; }
        public string PTS { get; set; }
    
        public virtual Region Region1 { get; set; }
    }
}
