//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorylicense
    {
        public long IDCategorylicense { get; set; }
        public string IDCategory { get; set; }
        public long IDlicense { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Driving_license Driving_license { get; set; }
    }
}
