//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driving_license
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Driving_license()
        {
            this.Categorylicense = new HashSet<Categorylicense>();
        }
    
        public long IDDrivinglicense { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public long Region { get; set; }
        public long Number { get; set; }
        public string GIBDDNumber { get; set; }
        public Nullable<long> Driver { get; set; }
        public byte[] Photo { get; set; }
        public string RegionBirth { get; set; }
        public Nullable<bool> Old { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Categorylicense> Categorylicense { get; set; }
        public virtual Drivers Drivers { get; set; }
        public virtual Region Region1 { get; set; }
    }
}
