//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OffencePunishment
    {
        public long IDFinePunishment { get; set; }
        public Nullable<long> IDOffence { get; set; }
        public Nullable<long> IDPunishment { get; set; }
    
        public virtual Offence Offence { get; set; }
        public virtual Punishment Punishment { get; set; }
    }
}
