//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public long IDRequest { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> Driver { get; set; }
        public Nullable<long> Status { get; set; }
        public Nullable<long> TypeRequest { get; set; }
    
        public virtual Drivers Drivers { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual TypeRequest TypeRequest1 { get; set; }
    }
}
